### ISSUE TITLE
Allow configuration of Nexus release and snapshot URLs 

### ISSUE THREAD

**Issue by jruaux** [kordamp/kordamp-parent#1]
For the gradle-nexus publish-plugin, `nexusUrl` is currently hard-coded to `https://s01.oss.sonatype.org/service/local/` which is for Sonatype users created after February 2021. For older users the url is `https://oss.sonatype.org/service/local/`.

**Comment by aalmiray** [comment]
Are you using this plugin for your own projects? If so that would be akin to using a personalized Maven pom from Kordamp on your own projects.

AFAICT `org.kordamp` has been migrated to the new URL this all projects under that domain should be already good to go.

**Comment by jruaux** [comment]
Yes I intend to use this plugin on projects that need to publish to maven central. I saw that you used it for the deploy step in jreleaser and wanted to do the same

**Comment by aalmiray** [comment]
Well in that case you'd have to adjust some of the default settings such as the entries in `people`, `license`, and URLs found in `links` and `scm`, otherwise the generated POM files for your projects will include Kordamp specific settings.

One more thing, for the time being Kordamp plugins do not fully work with Gradle 7.x due to breaking compatibility changes introduced by Gradle 7. We'll fix this of course but it will take a few more months to get it done.

**Comment by jruaux** [comment]
Sounds good. Thanks for all that good stuff!

**Comment by aalmiray** [comment]
I'd recommend building a local snapshot and try it out in your projects. Please file tickets for any additional issues/items that need to be more generic for non-Kordamp projects. I'll wait a few days before posting a new release.
